var OX_ffbdcea20b = '';
OX_ffbdcea20b += "<"+"script type=\"text/javascript\"><"+"!--\n";
OX_ffbdcea20b += "google_ad_client = \"ca-pub-3344983968687341\";\n";
OX_ffbdcea20b += "/* Pavé cours Informatique */\n";
OX_ffbdcea20b += "google_ad_slot = \"6473603646\";\n";
OX_ffbdcea20b += "google_ad_width = 300;\n";
OX_ffbdcea20b += "google_ad_height = 250;\n";
OX_ffbdcea20b += "google_ad_region= \"test\";\n";
OX_ffbdcea20b += "//-->\n";
OX_ffbdcea20b += "<"+"/script>\n";
OX_ffbdcea20b += "<"+"script type=\"text/javascript\"\n";
OX_ffbdcea20b += "src=\"http://pagead2.googlesyndication.com/pagead/show_ads.js\">\n";
OX_ffbdcea20b += "<"+"/script>\n";
OX_ffbdcea20b += "<"+"div id=\'beacon_ffbdcea20b\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'>\n";
OX_ffbdcea20b += "<"+"img src=\"http://cas.criteo.com/delivery/lg.php?ckmode=0&bannerid=0&campaignid=0&zoneid=5015&pb=1&bizmodel=0&catCol=0&catId=0&cb=ffbdcea20b&rtb=0&zc=%257caewq4ed7FA3Ri62tJniLFg%253d%253d%257c&b=_%25252fLqVauF2f3GKuekfelxxrA%25253d%25253d&bi=%7caewq4ed7FA1AR%2bUIuhYtq6MeZMtUKohJNnypEDXc%2fJUmDLOoKauhWQ%3d%3d%7c&loc=http%3a%2f%2fwww.siteduzero.com%2ftutoriel-3-102990-1-parametres-de-servlets.html&referer=http%3a%2f%2fwww.siteduzero.com%2ftutoriel-3-100324-1-tp-la-loteriez.html&c=hI4L3dqJAJHr3-Hxit8AW0XY2hNZ-Cn3&iii=167838266\" width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' />\n";
OX_ffbdcea20b += "<"+"/div><"+"div id=\"cton_d\" style=\"display:none\"><"+"/div>\n";
OX_ffbdcea20b += "<"+"script type=\"text/javascript\">\n";
OX_ffbdcea20b += "var cton_u = location.protocol + \'//nt.criteo.com/ref/notify.aspx?z=5015&d=ffbdcea20b\', cton_f = 10;function cton_n(){if(Math.random()*1000<"+"cton_f){var b=document.getElementById(\"cton_d\"),a;if(b!=null&&b.appendChild&&document.createElement){try{cton_u+=\"&u0=\"+escape(document.location)}catch(c){}try{cton_u+=\"&u1=\"+escape(document.referrer)}catch(c){}a=document.createElement(\"IMG\");if(a){b.appendChild(a);a.src=cton_u}}}}cton_n();\n";
OX_ffbdcea20b += "<"+"/script>\n";
document.write(OX_ffbdcea20b);
